### ISSUE TITLE
Docker does not start after "wasabi.sh bootstrap" with Docker version upgraded

### ISSUE THREAD

**Issue by iizrailevsky** [intuit/wasabi#100]
I did "wasabi.sh bootstrap" which upgraded my Docker version. However Docker was NOT started automatically when running "wasabi.sh start" and I got "sleep" messages instead:

```
$ ./bin/wasabi.sh start
chill'ax 🍺 
chill'ax 🍺 
chill'ax 🍺 
chill'ax 🍺 
chill'ax 🍺 
chill'ax 🍺 
```

**Comment by jwtodd** [comment]
see: feature/bug-osx-docker-start

**Comment by iizrailevsky** [comment]
Fixed now! 👍  @jwtodd @shoeffner
