### ISSUE TITLE
Cannot Get Working with Remote Cassandra

### ISSUE THREAD

**Issue by michaelgrosser** [intuit/wasabi#256]
First off, the documentation around this needs significant improvement. Right now it is very unclear and requires tons of fuss just to get the basics working.

After that, I'm still unable to get the wasabi container running. I did the build, I did the migrations. All of that worked and the keyspaces and tables exist on my remote Cassandra cluster. Wasabi itself simply will not start successfully and it seems to be because of this error I see in the Docker logs for the container:
`162161 [main] ERROR c.i.w.c.d.DefaultCassandraDriver - Exception occurred while connecting to the cluster...
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /10.128.1.23:9042: java.lang.RuntimeException: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.cassandra.exceptions.InvalidRequestException: Key may not be empty`

Here is what I have in my POM.xml (sensitive details masked):
`        <cassandra.username>my_cassandra_username</cassandra.username>
        <cassandra.password>my_cassandra_password</cassandra.password>
        <cassandra.experiments.keyspaceName>wasabi_experiments</cassandra.experiments.keyspaceName>
        <cassandra.experiments.nodeHosts>10.128.1.23</cassandra.experiments.nodeHosts>
        <cassandra.experiments.port>9042</cassandra.experiments.port>`

And here is the command I'm using to attempt to start Wasabi:
`MYSQL_HOST="my_endpoint.rds.amazonaws.com" NODE_HOST="10.128.1.23" ./bin/wasabi.sh start:wasabi`

When I run that it just hangs and then eventually returns:
`chill'ax error: not started`

Despite that, the Docker container is running but does not successfully respond on 8080. 

I could use any insight on what might be wrong here as everything appears configured properly and there doesn't seem to be a good reason for a Cassandra authentication exception. Additionally, I have no problem connecting to the remote cluster from this instance using cqlsh.

**Comment by michaelgrosser** [comment]
I resolved this. 

There are two problems here:
1. The instructions are very unclear in that you need to build with remote credentials setup.
2. You can't actually build with remote credentials setup because there's a very ill-conceived unit test assertion looking for the default username and password for the MySQL DB.

**Comment by symadept** [comment]
I am having the same issue, @michaelgrosser can you elaborate what you did here?

Thank you very much

**Comment by yinyuxuan2016** [comment]
Having the same issue, @michaelgrosser would be very useful if you can provide more info!
