### ISSUE TITLE
Where to view event payloads?

### ISSUE THREAD

**Issue by cbourdage** [intuit/wasabi#259]
We have this implemented without too many issues and I'm trying to better understand all of the features around Wasabi in regards to the api. One thing I haven't made sense of just yet is what is the purpose of the event payloads that are optional with events. I can't find any place in the admin panel where this may show up or how to see this data in anyway.

Is there any information available on how to use the payloads or where to view the payloads that are provided?

**Comment by iizrailevsky** [comment]
Glad Wasabi is working for you @cbourdage!

Event payloads can be passed with events. However they're presently not used for real-time Admin UI analytics. At Intuit, we do export these into our big data cluster via the pluggable export functionality and use these for offline analytics.

Hope this helps.

**Comment by cbourdage** [comment]
Thank you for the explanation. Just wanted to make sure I wasn't missing something. I was assuming it was just available for custom offline reporting.
