### ISSUE TITLE
Ability to force assign a user to a particular bucket for an experiment

### ISSUE THREAD

**Issue by deathweaselx86** [intuit/wasabi#310]
Could the ability to force assign a user to a particular bucket for an experiment be a thing? Even if it's just through a query parameter. That would really help.

**Comment by deathweaselx86** [comment]
Anything? This is a real problem for QA here.

**Comment by yoshprogrammer** [comment]
You could put together a simple python script or similar that would take in a user id and update the Cassandra database to force a user's bucket. @deathweaselx86

**Comment by thegyro** [comment]
@deathweaselx86 Hi! Sorry for the late response. We do have a `PUT` API for this. 

You can hit `/v1/assignments/applications/<application_name>/experiments/<experiment_label>/users/<user_id>`

With request body 
```
{
  assignment: <bucket>
}
```

This should force assign the specific user to the bucket of your choice.

**Comment by deathweaselx86** [comment]
Great! Thanks!
