### ISSUE TITLE
Hadoop/Kafka Integration

### ISSUE THREAD

**Issue by mandoz** [intuit/wasabi#313]
Is there a more detailed explanation of how to do the real-time streaming of data to Kafka for example?

There is this part in the documentation: https://intuit.github.io/wasabi/v1/guide/index.html#extending-server-side-modules

It is not very clear to me how to bind my class so it starts ingesting this data.

**Comment by thegyro** [comment]
@mandoz Hi! As given in the link, there are two classes you create 1) One is your custom `IngestionExecutor` which extends the `AssignmentIngestionExecutor` provided by Wasabi. 2) Your custom Assignments module where you do the binding as described. 

Inside the `execute()` method, you can submit your jobs. Let's say that you want to push the data to Kafka. The straightforward way of doing it is just put the logic for sending data to Kafka inside the `execute()` method. This would be synchronous though. You can also do it asynchronously by submitting a job to a `ThreadPoolExecutor` inside the `execute()` method. 

Internally, as Wasabi does an assignment, it also executes the custom `Executor` you have created and configured.  

Please let me know if you need any more clarification.

**Comment by mandoz** [comment]
@thegyro thanks a lot for the info!
