### ISSUE TITLE
Replace Cassandra with Dynamodb.

### ISSUE THREAD

**Issue by nutzhub** [intuit/wasabi#371]
Hi, this is awesome project!. So I've got assignment to change Cassandra to AWS DynamoDB. Do you have guideline or any suggestions?

**Comment by code-x-coffee** [comment]
@nut-abctech did you get anywhere with this?

**Comment by nutzhub** [comment]
@utsav-upendra not yet. seem like this project discontinue

**Comment by igorgolovanov** [comment]
Amazon now supports Cassandra in their AWS Managed Cassandra Service  - https://aws.amazon.com/ru/mcs/

**Comment by nutzhub** [comment]
this project stop maintain. I close this issue
