### ISSUE TITLE
[Questions] Can Wasabi run without Cassandra ?

### ISSUE THREAD

**Issue by kishorekkota** [intuit/wasabi#375]
Hello,

Not sure if anyone tried this or not. I am interested in trying to see if this can be used as a FeaturFlag and A / B testing tool - with MYSQL ( Maria DB ). Is there any option to not use Cassandra as we do not have analytics requirement ?

**Comment by mrids** [comment]
original code used mysql and redis so yes its possible, but will need to
reinstate that in a different branch if needed.

-mita

**Comment by kishorekkota** [comment]
Thank you.
