### ISSUE TITLE
Mobile + JavaScript

### ISSUE THREAD

**Issue by gsogol** [intuit/wasabi#4]
Is the assumption that one would write wrappers or SDKs for JavaScript and native device languages to interface with the API? 

In other words, is right now what's available just an API? This looks fantastic though. Thanks for open sourcing.

**Comment by tariqislam** [comment]
Hi gsogol,

Currently we don't have any language-specific SDKs to interact with the API, so what's available at the moment is just the API. But please feel free to contribute, and we'll definitely look forward to that!

Thanks.

Tariq

**Comment by Faedrivin** [comment]
Hi @gsogol ,

what do you expect from such an SDK? I created a small [spike](https://github.com/Faedrivin/wasabi/tree/develop/contrib/SDK/JavaScript). You can configure an application and a server in the `wasabi.config.js`, create an AB object (take a look at the `index.html`), retrieve user assignments (`abtest.assignment(experiment, user, callback)`) and register event listeners for posting actions or impressions (which basically are just another type of actions).

I suggest you to spin up your local environment, create an experiment named "JavaScriptDemoExp" in an application "JavaScriptDemoApp" with 100% sampling rate and just 1 100% bucket (don't forget to start it) and then just open up the index.html to see what it is capable of. Note that this is really just a small scribbled idea, nothing production ready or anything.

I think an SDK should not need to support much more (maybe batch assignments are a thing), but we are interested in what you are looking for. 

Thanks for stepping into the conversation
Sebastian

**Comment by Faedrivin** [comment]
Hi again @gsogol ,

there is also [wasabi.js](https://github.com/intuit/wasabi/blob/d52de577f0aa6c26727eba4e72e66969adc762fb/modules/ui/app/scripts/wasabi.js) which already allows lots of functionality. For a demonstration see our [hello world demo](https://github.com/intuit/wasabi/tree/d52de577f0aa6c26727eba4e72e66969adc762fb/contrib/hello-world) which contains a simple usage example.

Is that what you are looking for?

Best
Sebastian

**Comment by shoeffner** [comment]
This seems to be no longer of interest.
