### ISSUE TITLE
contrib a simple single-node terraform deploy script

### ISSUE THREAD

**Issue by jwtodd** [intuit/wasabi#56]
goal: add a simple aws terraform deployment script

- [ ] assume package (eg wasabi.rpm) is built local
- [ ] instantiate single ec2 node, reasonably locked down and durable storage not required
- [ ] yum install: java, cassandra, mysql (may not need runit)
- [ ] rpm install wasabi
- [ ] start wasabi
- [ ] open external port
- [ ] test via % ./bin/wasab.ish -e IP:8080 test
- [ ] destroy instance
- [ ] commit as a contrib project

**Comment by shoeffner** [comment]
Closing this, #80 was merged.
