### ISSUE TITLE
filter test source tests from coveralls

### ISSUE THREAD

**Issue by jwtodd** [intuit/wasabi#6]
**goal:** [coveralls](https://coveralls.io/github/intuit/wasabi?branch=develop) coverage should exclude test source code

**see:**
- [coveralls plugin](https://github.com/trautonen/coveralls-maven-plugin)
- [jacoco plugin](http://www.eclemma.org/jacoco/trunk/doc/maven.html)
- [cobertura plugin](http://www.mojohaus.org/cobertura-maven-plugin)

**note:** might need to add exclusions to jacoco, cobertura or both

**Comment by jwtodd** [comment]
goal: coveralls coverage should exclude test source code

**Comment by wasabi-honeybadger** [comment]
@iizrailevsky i think we have unit test parity. concur?

**Comment by iizrailevsky** [comment]
@jwtodd +1 we're good here now! 👍  Unit test coverage matches internal sonar coverage. This is now complete.
