### ISSUE TITLE
How to run on Linux

### ISSUE THREAD

**Issue by vinodtalati** [intuit/wasabi#68]
Hi 
I was trying to get the package deployed on linux. I got wasabi.sh to build the rpm and deb packages and the tried installing on ubuntu with "dpkg -i". Cant seem to find it on the system after installation.

Are there any docs available on how to get this configured and working? 

```
vinod@vinod-virtual-machine:~/Desktop$ sudo dpkg -i wasabi.deb 
(Reading database ... 166492 files and directories currently installed.)
Preparing to unpack wasabi.deb ...
Unpacking wasabi-main-build (1.0.20160801220857-SNAPSHOT-20160818173207) over (1.0.20160801220857-SNAPSHOT-20160818173207) ...
Setting up wasabi-main-build (1.0.20160801220857-SNAPSHOT-20160818173207) ...
vinod@vinod-virtual-machine:~/Desktop$
```

**Comment by jwtodd** [comment]
hey @vinodtalati -

  welcome to wasabi :)

  firstly there were some updates to the project specifically in this area recently to let's ensure you have a fresh 'git pull' of the develop (ie default) branch.

  ok, i haven't used dpkg for awhile now. we do deploy the rpm build internally using this same process.

  the app should, by default, install into the /usr/local/wasabi-[version] directory.

  additionally, a wasabi user and group should be created with which the wasabi process is owned.

  i can try installing the deb package against an ubuntu image shortly, noting again we are more familiar, operationally, with the rpm build.

  hth,

james

**Comment by vinodtalati** [comment]
Thanks @jwtodd That helped a lot. I got the server running and talking to cassandra & mysql in my Ubuntu VM. Working on getting the UI running now. Keeping notes on it all so will try and update the docs when done.

**Comment by jwtodd** [comment]
*suhweet*

love it!

keep going buddy!

btw, we are going to gen an rpm/deb file for the wasabi-ui as well rsn ... if you look in under the [ws]/modules/ui/bin you will see an fpm.sh script ... that is  not unlike the one in [ws]/bin/fpm.sh

**Comment by iizrailevsky** [comment]
Great @vinodtalati!!

By the way, feel free to join on Gitter chat: https://gitter.im/intuit/wasabi (invitation sent to your email)

**Comment by shoeffner** [comment]
Since the feature is implemented I guess we can close this issue now.
