### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by jwtodd** [intuit/wasabi#7]
**goal:** [travis](travis-ci.org/intuit/wasabi) should be able to successfully push signed artifacts, SNAPSHOT and milestone, to [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.intuit.wasabi%22)

**see:** #21 

**steps:**
- [ ] create signing certificate
- [ ] configure repo/travis with authorized certificate

**Comment by jwtodd** [comment]
**goal:** [travis](travis-ci.org/intuit/wasabi) should be able to successfully push signed artifacts, SNAPSHOT and milestone, to [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.intuit.wasabi%22)

**Comment by wasabi-honeybadger** [comment]
addressed in #21
