### ISSUE TITLE
wasabi package doesn't work without JAVA_HOME setup

### ISSUE THREAD

**Issue by aqua0ps** [intuit/wasabi#79]
You have to setup the JAVA_HOME additionally to make it work in OSX
export JAVA_HOME=`/usr/libexec/java_home`

**Comment by jwtodd** [comment]
@vinodtalati the following lines in [ws]/bin/fpm.sh fail on osx where users do not specify JAVA_HOME:

```bash
export JAVA_HOME=${JAVA_HOME:-/usr/local/java}
export PATH=$JAVA_HOME/bin:$PATH
```

q: are these lines required for all supported environments?

if so, then for OSX we should set the default value to `/usr/libexec/java_home`

q: if we do have to set JAVA_HOME then does `/usr/libexec/java_home` exist on linux?

i am hoping we can remove explicitly setting JAVA_HOME :)

**Comment by vinodtalati** [comment]
@jwtodd This should be removed.

The path /usr/libexec/java_home doesn't exit on linux. This is only for mac. 
The Ubuntu patch we added does everything required for Linux inside the bootstrap method (in wasabi.sh). For Mac the JAVA_HOME was never set anywhere. It could be added to bootstrap as well. 

In any case the lines you mentioned in fpm.sh should not be there.

**Comment by jwtodd** [comment]
ok thx @vinodtalati i will spin up a PR

much appreciated!
