### ISSUE TITLE
package installation error on Ubuntu

### ISSUE THREAD

**Issue by vinodtalati** [intuit/wasabi#82]
I am seeing some errors when trying to install the .deb packages on Ubuntu. 

wasabi-main-*.deb complains about missing dependencies: null and object.

wasabi-ui-*.deb complains about missing folders. One of the paths in the script is incorrect and needs updating. Here is the ui.deb file installation log:

```
sudo dpkg -i wasabi-ui-build_1.0.20160826233241-SNAPSHOT-20160831173901_all.deb
Selecting previously unselected package wasabi-ui-build.
(Reading database ... 178494 files and directories currently installed.)
Preparing to unpack wasabi-ui-build_1.0.20160826233241-SNAPSHOT-20160831173901_all.deb ...
Unpacking wasabi-ui-build (1.0.20160826233241-SNAPSHOT-20160831173901) ...
Setting up wasabi-ui-build (1.0.20160826233241-SNAPSHOT-20160831173901) ...
chown: cannot access '/usr/local/wasabi-1.0.20160826233241-SNAPSHOT-build/../wasabi-ui-1.0.20160826233241-SNAPSHOT-build': No such file or directory
cp: cannot stat '/usr/local/wasabi-1.0.20160826233241-SNAPSHOT-build/../wasabi-ui-1.0.20160826233241-SNAPSHOT-build/content/ui/dist/*': No such file or directory
The chown and cp commands need to point to /usr/local/wasabi-main-1.0.20160826233241-SNAPSHOT-build
```

After installation apt is also broken. If we try to install any packages after then apt prompts to remove the wasabi-main*.deb package. Not sure if this problem exists with rpm.

**Comment by jwtodd** [comment]
ok @vinodtalati ... will work to verify installation against a local ubuntu container soon.

thx for the thorough writeup compadre :)

**Comment by vinodtalati** [comment]
@jwtodd I poked around a bit and seemed to be an easy fix, so I fixed it. :)
Pls see my pull request.

**Comment by shoeffner** [comment]
Thanks @vinodtalati , we pulled it in. Worked well on our single node deployment!
