### ISSUE TITLE
get all integration tests to pass

### ISSUE THREAD

**Issue by jwtodd** [intuit/wasabi#9]
**goal:** get all integration tests to pass green

**steps:**
- [ ] % ./bin/wasabi.sh start test stop

**Comment by jwtodd** [comment]
goal: get all integration tests to pass green

steps: % ./bin/wasabi.sh start test stop

**Comment by shoeffner** [comment]
Was this achieved in #58 ?

**Comment by shoeffner** [comment]
As of https://github.com/intuit/wasabi/pull/78#issuecomment-246445164 I consider this solved.
